async function getWeatherData(location) {
	const requestString = `https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/${location}?key=VK2YN8PQWPJW6MM627KLFY4WC`;

	const response = await fetch(requestString, {
		mode: 'cors',
	});

	if (!response.ok) console.error('Failed to connect to API');

	return formatJson(await response.json());
}

function formatJson(jsonData) {
	const weatherData = {
		location: jsonData.resolvedAddress,
		description: jsonData.description,
		currentConditions: formatDay(jsonData.currentConditions),
		days: jsonData.days.map(formatDay),
		alerts: jsonData.alerts,
		timezone: jsonData.timezone,
	};

	return weatherData;
}

function formatDay(jsonDay) {
	const day = {
		time: jsonDay.datetime,
		conditions: jsonDay.conditions,
		temp: Math.round(Number((jsonDay.temp - 32) / 1.8)),
		feelsLike: Math.round(Number((jsonDay.feelslike - 32) / 1.8)),
		humidity: jsonDay.humidity,
		windSpeed: jsonDay.windspeed,
		windGust: jsonDay.windgust,
		windDir: jsonDay.winddir,
		uvIndex: jsonDay.uvindex,
		snow: jsonDay.snow,
		sunrise: jsonDay.sunrise,
		sunset: jsonDay.sunset,
		icon: `./src/img/svg/weather-icons/${jsonDay.icon}.svg`,
	};

	return day;
}

function getDummy() {
	return {
		location: 'London, England, United Kingdom',
		description:
			'Similar temperatures continuing with a chance of rain tomorrow & Monday.',
		currentConditions: {
			time: '06:27:00',
			conditions: 'Partially cloudy',
			temp: 10,
			feelsLike: 8,
			humidity: 70.8,
			windSpeed: 10.3,
			windGust: 27.5,
			windDir: 212,
			uvIndex: 0,
			snow: 0,
			sunrise: '07:52:14',
			sunset: '15:52:01',
			icon: './src/img/svg/weather-icons/partly-cloudy-night.svg',
		},
		days: [
			{
				time: '2024-12-07',
				conditions: 'Rain, Overcast',
				temp: 8,
				feelsLike: 4,
				humidity: 73.7,
				windSpeed: 27.9,
				windGust: 53.7,
				windDir: 267.7,
				uvIndex: 0,
				snow: 0,
				sunrise: '07:52:14',
				sunset: '15:52:01',
				icon: './src/img/svg/weather-icons/rain.svg',
			},
			{
				time: '2024-12-08',
				conditions: 'Rain, Overcast',
				temp: 7,
				feelsLike: 4,
				humidity: 78.7,
				windSpeed: 17.7,
				windGust: 44.3,
				windDir: 354.2,
				uvIndex: 2,
				snow: 0,
				sunrise: '07:53:22',
				sunset: '15:51:46',
				icon: './src/img/svg/weather-icons/rain.svg',
			},
			{
				time: '2024-12-09',
				conditions: 'Rain, Partially cloudy',
				temp: 7,
				feelsLike: 4,
				humidity: 74.5,
				windSpeed: 14.3,
				windGust: 35.8,
				windDir: 27.1,
				uvIndex: 2,
				snow: 0,
				sunrise: '07:54:29',
				sunset: '15:51:34',
				icon: './src/img/svg/weather-icons/rain.svg',
			},
			{
				time: '2024-12-10',
				conditions: 'Partially cloudy',
				temp: 5,
				feelsLike: 2,
				humidity: 75.3,
				windSpeed: 9.2,
				windGust: 21.7,
				windDir: 22.8,
				uvIndex: 0,
				snow: 0,
				sunrise: '07:55:33',
				sunset: '15:51:25',
				icon: './src/img/svg/weather-icons/partly-cloudy-day.svg',
			},
			{
				time: '2024-12-11',
				conditions: 'Partially cloudy',
				temp: 5,
				feelsLike: 3,
				humidity: 76.6,
				windSpeed: 7.6,
				windGust: 17.7,
				windDir: 31.8,
				uvIndex: 1,
				snow: 0,
				sunrise: '07:56:34',
				sunset: '15:51:21',
				icon: './src/img/svg/weather-icons/partly-cloudy-day.svg',
			},
			{
				time: '2024-12-12',
				conditions: 'Partially cloudy',
				temp: 5,
				feelsLike: 3,
				humidity: 75.1,
				windSpeed: 5.8,
				windGust: 17.9,
				windDir: 59.4,
				uvIndex: 1,
				snow: 0,
				sunrise: '07:57:33',
				sunset: '15:51:19',
				icon: './src/img/svg/weather-icons/partly-cloudy-day.svg',
			},
			{
				time: '2024-12-13',
				conditions: 'Partially cloudy',
				temp: 4,
				feelsLike: 2,
				humidity: 74,
				windSpeed: 9.4,
				windGust: 20.1,
				windDir: 46.4,
				uvIndex: 1,
				snow: 0,
				sunrise: '07:58:29',
				sunset: '15:51:21',
				icon: './src/img/svg/weather-icons/partly-cloudy-day.svg',
			},
			{
				time: '2024-12-14',
				conditions: 'Overcast',
				temp: 5,
				feelsLike: 4,
				humidity: 62.4,
				windSpeed: 4,
				windGust: 6.9,
				windDir: 79.8,
				uvIndex: 1,
				snow: 0,
				sunrise: '07:59:21',
				sunset: '15:51:26',
				icon: './src/img/svg/weather-icons/cloudy.svg',
			},
			{
				time: '2024-12-15',
				conditions: 'Clear',
				temp: 4,
				feelsLike: 4,
				humidity: 61.9,
				windSpeed: 3.4,
				windGust: 4,
				windDir: 135.5,
				uvIndex: 2,
				snow: 0,
				sunrise: '08:00:12',
				sunset: '15:51:35',
				icon: './src/img/svg/weather-icons/clear-day.svg',
			},
			{
				time: '2024-12-16',
				conditions: 'Partially cloudy',
				temp: 3,
				feelsLike: 3,
				humidity: 83,
				windSpeed: 4.2,
				windGust: 12.8,
				windDir: 355.3,
				uvIndex: 1,
				snow: 0,
				sunrise: '08:00:59',
				sunset: '15:51:47',
				icon: './src/img/svg/weather-icons/partly-cloudy-day.svg',
			},
			{
				time: '2024-12-17',
				conditions: 'Partially cloudy',
				temp: 3,
				feelsLike: 2,
				humidity: 82.6,
				windSpeed: 4.3,
				windGust: 9.8,
				windDir: 197.5,
				uvIndex: 2,
				snow: 0,
				sunrise: '08:01:43',
				sunset: '15:52:03',
				icon: './src/img/svg/weather-icons/partly-cloudy-day.svg',
			},
			{
				time: '2024-12-18',
				conditions: 'Partially cloudy',
				temp: 3,
				feelsLike: 1,
				humidity: 82.5,
				windSpeed: 4,
				windGust: 9.8,
				windDir: 94.7,
				uvIndex: 2,
				snow: 0,
				sunrise: '08:02:24',
				sunset: '15:52:22',
				icon: './src/img/svg/weather-icons/partly-cloudy-day.svg',
			},
			{
				time: '2024-12-19',
				conditions: 'Overcast',
				temp: 4,
				feelsLike: 3,
				humidity: 81.3,
				windSpeed: 4.3,
				windGust: 11.3,
				windDir: 40.8,
				uvIndex: 1,
				snow: 0,
				sunrise: '08:03:02',
				sunset: '15:52:44',
				icon: './src/img/svg/weather-icons/cloudy.svg',
			},
			{
				time: '2024-12-20',
				conditions: 'Overcast',
				temp: 5,
				feelsLike: 1,
				humidity: 83.9,
				windSpeed: 14.3,
				windGust: 28.4,
				windDir: 74.9,
				uvIndex: 0,
				snow: 0,
				sunrise: '08:03:36',
				sunset: '15:53:10',
				icon: './src/img/svg/weather-icons/cloudy.svg',
			},
			{
				time: '2024-12-21',
				conditions: 'Partially cloudy',
				temp: 3,
				feelsLike: -2,
				humidity: 66.8,
				windSpeed: 14.3,
				windGust: 29.3,
				windDir: 100.6,
				uvIndex: 2,
				snow: 0,
				sunrise: '08:04:08',
				sunset: '15:53:39',
				icon: './src/img/svg/weather-icons/partly-cloudy-day.svg',
			},
		],
		alerts: [
			{
				event: 'Yellow wind warning',
				headline:
					'Strong winds associated with Storm Darragh likely leading to some disruption and damage.: UPDATED',
				ends: '2024-12-08T06:00:00',
				endsEpoch: 1733637600,
				onset: '2024-12-06T15:00:00',
				onsetEpoch: 1733497200,
				id: '2.49.0.0.826.0.GB_241206105936_afa8586f.v3.0.W',
				language: 'en',
				link: 'https://www.metoffice.gov.uk/weather/warnings-and-advice/uk-warnings',
				description:
					'Information on update: Extended warning north to include parts of the Central Belt and eastern coast of Scotland. Storm Darragh is likely to cross Ireland late Friday, then parts of England and Wales on Saturday, clearing to the east of England on Saturday night or early Sunday. Darragh could bring a period of strong winds to much of the warning area. Winds will initially be from a southerly direction, but the strongest winds are likely as the low clears away when northerly or northwesterly winds may quite widely gust to around 40-50 mph inland but locally could gust in excess of 60 mph. Around coasts, winds may gust to 60-70 mph, perhaps locally nearer 80 mph. The wind may cause disruption to travel, with difficult driving conditions likely. The duration of the strongest winds in any one location is likely to be less than 24 hours, but this warning is for a more extended period to cover the passage of the strong winds over the whole country. These start in the west on Friday evening, and clear from the east coast of England early on Sunday.\n\nWhat should I do?\n\nPrepare to protect your property and people from injury. Check for loose items outside your home and plan how you could secure them. Items include; bins, garden furniture, trampolines, tents, sheds, and fences. \n\nGive yourself the best chance of avoiding delays by checking road conditions if driving, or bus and train timetables, amending your travel plans if necessary.\n\nPeople cope better with power cuts when they have prepared for them in advance. It’s easy to do; consider gathering torches and batteries, a mobile phone power pack and other essential items.\n\nIf you are on the coast, stay safe during stormy weather by being aware of large waves. Even from the shore large breaking waves can sweep you off your feet and out to sea. Take care if walking near cliffs; know your route and keep dogs on a lead. In an emergency, call 999 and ask for the Coastguard.\n\nCheck if your property could be at risk of flooding. If so, consider preparing a flood plan and an emergency flood kit.\n\nBe prepared for weather warnings to change quickly: when a weather warning is issued, the Met Office recommends staying up to date with the weather forecast in your area. For further details see https://www.metoffice.gov.uk/weather/warnings-and-advice/uk-warnings',
			},
		],
		timezone: 'Europe/London',
	};
}

export { getWeatherData, getDummy };
